(defpackage #:project-euler/problems/p0023-non-abundant-sums
    (:nicknames #:p0023)
    (:use #:cl #:project-euler/commons)
    (:export #:solve))
(in-package #:project-euler/problems/p0023-non-abundant-sums)

(defun main (limit)
    (let* ( (full-limit limit)
            (half-limit (+ 1 (ash limit -1)))
            (divisor-sums (make-array full-limit :initial-element 0 :element-type '(unsigned-byte 24)))
            (abundant-numbers '())
            (non-abundant-numbers (make-array full-limit :initial-element 1 :element-type 'bit))
            (sum 0))
    ;; sieving approach to get sum of proper divisors
    (do ((n 1 (+ 1 n))) ((= half-limit n))
        (do ((nn (* 2 n) (+ nn n))) ((>= nn full-limit))
            (incf (aref divisor-sums nn) n)))
    (setf abundant-numbers (do ((n 1 (+ 1 n))) ((= n full-limit) (reverse abundant-numbers))
        (when (< n (aref divisor-sums n)) (push n abundant-numbers))))
    (when (= 30 limit) (print abundant-numbers) (terpri))
    (dolist (n1 abundant-numbers)
        (dolist (n2 abundant-numbers)
            (if (< (+ n1 n2) full-limit)
                (setf (sbit non-abundant-numbers (+ n1 n2)) 0)
                (return nil))))
    (when (= 30 limit) (print non-abundant-numbers) (terpri))
    (do ((n 1 (+ n 1))) ((= (min limit 28124) n) sum)
        (when (= 1 (sbit non-abundant-numbers n)) (incf sum n)))))

(defun solve () (main 28124))
